// Code generated by 'option-gen'. DO NOT EDIT.

package kube

import (
	prompt "github.com/hoseinalirezaee/kube-prompt/prompt"
)

var clusterInfoOptions = []prompt.Suggest{
	prompt.Suggest{Text: "--include-extended-apis", Description: "If true, include definitions of new APIs via calls to the API server. [default true]"},
}
