name: release
on:
  push:
    tags:
    - v*.*.*

permissions:
  contents: write

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      id: go
      with:
        check-latest: true
        go-version-file: go.mod

    - name: Build artifacts
      run: make cross

    - name: Publish release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "$GITHUB_REF_NAME" pkg/* \
          --verify-tag \
          --title "$GITHUB_REF_NAME" \
          --notes "Release $GITHUB_REF_NAME"
